### ISSUE TITLE
Site: text selection color in code-blocks

### ISSUE THREAD

**Issue by fahad19** [Travix-International/frint#146]
Currently shows a dark color, which doesn't really go with rest of the site:

![screen shot 2017-03-21 at 13 13 20](https://cloud.githubusercontent.com/assets/20046/24146942/51ea4220-0e38-11e7-87ec-96b8a8e5cd59.png)

**Comment by fahad19** [comment]
This tutorial would be handy: https://css-tricks.com/almanac/selectors/s/selection/

**Comment by AlexDudar** [comment]
which one do you like:

<img width="684" alt="screen shot 2017-04-23 at 6 41 20 pm" src="https://cloud.githubusercontent.com/assets/3122478/25315408/b5caff06-2854-11e7-98a5-354caed50c50.png">

<img width="677" alt="screen shot 2017-04-23 at 6 41 33 pm" src="https://cloud.githubusercontent.com/assets/3122478/25315409/b84e2df2-2854-11e7-8393-6458e4ef7fd9.png">

**Comment by fahad19** [comment]
second one looks great!
