### ISSUE TITLE
Site: search functionality in the documentation

### ISSUE THREAD

**Issue by markvincze** [Travix-International/frint#153]
Add a search bar to the documentation to be able to search.
An example can be the search bar used in Gitbook, for example here: https://codiechanel.gitbooks.io/gitbook-demo/content/

**Comment by fahad19** [comment]
Algolia could be considered: https://www.algolia.com/ref/docsearch

React (and many others) use it: https://facebook.github.io/react/

**Comment by markvincze** [comment]
Ok, I'll look into Algolia docsearch

**Comment by fahad19** [comment]
Update: I have submitted frint.js.org on Algolia earlier today. And waiting for them to provide me with the snippet code for adding to our site.

I will update here again once I receive it from them.

**Comment by markvincze** [comment]
Oops, me too ^^

**Comment by fahad19** [comment]
It's fine :)

Whoever receives a response from them earlier can post it here. and then you can send a PR.
