### ISSUE TITLE
Add preinstall script to run npm install recursively for all packages

### ISSUE THREAD

**Issue by yurist38** [Travix-International/frint#201]
Should we add `preinstall` script to main `package.json` for easy installing node modules for all packages before installing root modules?

**Comment by fahad19** [comment]
`lerna bootstrap`?

https://github.com/lerna/lerna/#bootstrap

**Comment by yurist38** [comment]
Ah, that works. Thanks!

**Comment by fahad19** [comment]
`npm run bootstrap` is there for convenience.
