### ISSUE TITLE
"streamProps" is not updating the props in certain cases

### ISSUE THREAD

**Issue by vasilibrutsky** [Travix-International/frint#202]
We've used in our application 'streamProps' for streaming props, but it's not mapping the updated store to props and as a result, in the widget we have outdated old props despite the actions and reducers work in correct way and state is correct. Here's the usage of the function:
`return streamProps({})
    .set(
      store.getState$(),
      state => state.carShow
    )`

**Comment by fahad19** [comment]
can you please isolate your issue, and reproduce it here? http://jsbin.com/cotatamiwu/edit?html,js,console

**Comment by fahad19** [comment]
Closing since there is no information on reproducing it.
