### ISSUE TITLE
Add ability to use components props in observe 

### ISSUE THREAD

**Issue by JutIgor** [Travix-International/frint#204]
Will be nice to have an access to components props (which is passed by parent) in observe. This feature can allow to perform some actions, get some stuff from "store" according to passed value, or even simply wrap up third-party component without creating the new one.
This proposal is inspired by react-redux package which allow to do same things.

**Comment by fahad19** [comment]
you raise a very interesting question, and thanks for that! we never thought of supporting it in `fn` of:

```js
observe(fn)(Component)
```

since it always expects the `app` instance. we will definitely think about it more.

but can you please share any existing use case for it?

**Comment by fahad19** [comment]
one possible API:

```js
observe(function (app, props$) {
  return Observable.of({});
})(RootComponent);
```

or make the second argument an object, and we can destruct the `props$` out of it:

```js
observe(function (app, { props$ }) {
  return Observable.of({});
})(RootComponent);
```

**Comment by alexmiranda** [comment]
I don't fully understand what the use cases would be, but as for your proposed APIs, I think option 2 (passes the `props$` observable as part of an extra object argument) is better and leads to a more clean and easy-to-maintain API in future.

**Comment by JutIgor** [comment]
@alexmiranda @fahad19 Just explaining without code: you often have cases when for example your data stored in store (or in some service in app), and component get key from parent. So it needs to take data from store, get the right data by key, and perform some actions, render, etc.
For now we can pass throw observe this data, and in render method get necessary data.

I guess the better way is in observe get the passed key, get data, and pass to component exact what it needs. So you don't do any additional actions in render method. Just display this data.

As I said before analogue of this approach is connect method from react-redux, which have an "ownProps" argument.

Sorry for the long answer :(

**Comment by fahad19** [comment]
@JutIgor: I am looking into it right now, as I hit a use case myself with dynamic routing using `frint-router-react`.
