### ISSUE TITLE
Proposal: frint-data

### ISSUE THREAD

**Issue by fahad19** [Travix-International/frint#257]
# `frint-data`

- [Models](#models)
  - [Creating class](#creating-class)
  - [Instantiation](#instantiation)
  - [Usage](#usage)
  - [Validation rules](#validation-rules)
  - [Difference between Types and Rules](#difference-between-types-and-rules)
- [Collections](#collections)
  - [Methods](#methods)
  - [Observing](#observing)
- [Embedding](#embedding)
- [Immutability](#immutability)

## Models

Models are for object-like data structures.

### Creating class

```js
import {
  Types,
  Rules,

  createSchema,

  createModel,
  createCollection,
} from 'frint-data';

const PostSchema = createSchema({
  id: Types.uuid,
  title: Types.string,
  body: Types.string
});

const Post = createModel({
  schema: PostSchema
});
```

### Instantiation

```js
const post = new Post({
  id: 'uuid here',
  title: 'Hello World',
  body: 'blah...',
});
```

### Usage

```js
post.get('title'); // Hello World

post.set('title', 'Hello Universe');
post.get('title'); // Hello Universe

post.get$().subscribe(attributes => console.log(attributes));
```

### Validation rules

```js
const PostSchema = createSchema({
  id: Types.uuid,
  title: {
    type: Types.uuid,
    rules: [
      // built-in rules
      Rules.isNotEmpty,

      // built-in rules with custom message
      {
        rule: Rules.isNotEmpty,
        message: 'Body must not be empty'
      },

      // custom rule/message
      {
        rule: function (modelInstance) {
          return true; // when valid
        },
        message: 'You screwed up your body'
      },

      // async validation
      {
        rule: function (modelInstance, done) {
          done(null); // done(errorMessage); null means it's all good
        }
      }
    ]
  }
});
```

to validate:

```js
const post = new Post({
  title: 'Hello World'
});

post.set('title', ''); // with set the value, and register a new vaildation error

post.getValidationErrors$().subscribe(errors => console.log(errors));
```

### Difference between Types and Rules

Type errors will prevent values being set in the first place.

Validation rule errors will set the value, but will raise a new validation error.

## Collections

Collections are for array-like data structures:

```js
const Posts = createCollection({
  model: Post
});

const posts = new Posts([
  modelInstance,

  // OR object following Model's schema
  {
    title: 'Hello World',
    body: 'blah...'
  }
]);

const firstPost = posts.at(0); // Post model's instance for first item in the list
```

### Methods

```js
posts.push(newModelInstance);
```

And more array like methods:

* filter
* map
* reduce
* ...etc

### Observing

```js
posts.get$().subscribe(postsPlainArray => console.log(postsPlainArray));
```

## Embedding

When defining schema, other Models or Collections can be set as types:

```js
const MyRootModel = createModel({
  schema: createSchema({
    posts: Types.collection.of(Posts)
    user: Types.model.of(User)
  })
});
```

Can be instantiated in one go:

```js
const myRootModel = new MyRootModel({
  posts: [
    { title: 'Hello World' }
  ],
  user: {
    name: 'Fahad',
    active: true,
  }
});

const postsCollectionInstance = myRootModel.get('posts');
const firstPostModelInstance = postsCollectionInstance.at(0);
firstPostModelInstance.get('title'); // Hello world
```

## Immutability

By default, all models can be immutable. Meaning, they cannot be mutated externally unless the Model definition supports it.

An example:

```js
const Post = createModel({
  schema: PostSchema,

  setTitle(title) {
    // `this.set()` can be made available to only instance methods
    this.set('title', title);
  },

  setDescription(description) {
    this.set('description', description);
  }
});

const post = new Post({ title: 'Hello World' });
post.setTitle('Hello Universe'); // sets title
post.set('title', 'Hello Univerwise'); // will not work
```

The access to `model.set()` can be made configurable. But I would prefer if they are not exposed publicly by default.

**Comment by viacheslaff** [comment]
I think it's a good idea to have definitions of data structures, data validation and making models read-only. Regarding the implementation, I have some suggestions:

1. It feels like we're trying to put **too many things** in one place. For example, models and collections can be separate from validation. When we're passing read-only model to some app, we don't need validation.
Also, IMHO, validation shouldn't be a property of a model instance. Validation can be applied to new data using validation rules, which are of course related to the schema, but I think can be separate.
2. I'm a bit worried, that with current proposal **model can contain invalid data** although it has validation rules embedded. Maybe we can only restrict types in the model, but values can be arbitrary (i.e. for storing temporary values while user fills in a form), and then apply validation rules whenever necessary.
3. I didn't get the **point of having both** `createSchema` and `createModel`, because they're always used in composition and `createModel` basically has only one parameter – `schema`. Is it for ability to provide model methods?
4. How about considering **using instance properties**? (because it's shorter and can be easier analyzed by IDE):
```js
post.get('title');
post.set('title', 'New title');
// vs
post.title;
post.title = 'New title';
```

**Comment by fahad19** [comment]
hey @viacheslaff, thanks for the input! I will respond to each point below:

> It feels like we're trying to put too many things in one place. For example, models and collections can be separate from validation. When we're passing read-only model to some app, we don't need validation. Also, IMHO, validation shouldn't be a property of a model instance. Validation can be applied to new data using validation rules, which are of course related to the schema, but I think can be separate.

I share similar views too. Validation can be separate from Models/Collections. Then the question comes, where does it go then?

When defining Schema for a Model, you are already setting 'types' info for the fields. So putting validation rules there means the developer has to maintain things per 'field' only in one place. 

I liked seeing how Ecto (Elixir) did it with Changesets concept. It would be worth checking how they do it, and see if we can translate it into a meaningful API in this spec: https://hexdocs.pm/ecto/Ecto.Changeset.html

Changesets can liberate validations from Schema.

> I'm a bit worried, that with current proposal model can contain invalid data although it has validation rules embedded. Maybe we can only restrict types in the model, but values can be arbitrary (i.e. for storing temporary values while user fills in a form), and then apply validation rules whenever necessary.

This is something that came up before too. Unlike ORMs in backend, Models in the browser do need to contain user input as they happen. Think of a Post model being used to render a form:

```js
import React from 'react';
import { observe, streamProps } from 'frint-react';

function PostForm(props) {
  return (
    <div>
      Title: 

      <input 
        onChange={e => props.handleTitleChange(e.target.value)}
        value={props.titleValue}
      />

     Errors: {props.validationErrors}
    </div>
  );
}

export default observe(function (app) {
  const post = new Post({
    title: 'Hello World',
  });

  return streamProps()
    .set(
      post.get$(),
      postAttrs => ({ titleValue: postAttrs.title })
    )
    .set('handleTItleChange', post.setTitle)
    .set(
      post.getValidationErrors$(),
      errors => ({ validationErrors: errors })
     )
    .get$();
})(PostForm);
```

I would welcome an alternative API if we can solve this problem.

> I didn't get the point of having both createSchema and createModel, because they're always used in composition and createModel basically has only one parameter – schema. Is it for ability to provide model methods?

Yes. Methods need to be allowed in Models, that will be defined when creating the Model class.

And by default, only methods defined in the Model will be allowed to change the attributes (values) to avoid unwanted mutations.

> How about considering using instance properties? (because it's shorter and can be easier analyzed by IDE):

This is something that I did previously in Tydel: http://tydel.js.org/intro/quickstart.html

The problem with that kind of approach is, soon you get confused which property is actually a value (attribute), and which one is a method.

And also limits the developer from using an attribute AND a method of the same name.

**Comment by mAiNiNfEcTiOn** [comment]
Sorry to interrupt the full conversation you guys are having, but what are you defining as validation?

I'd split the validation in 2 things:

  - _Type_ validation - Based on the property/attribute's type definition, you should error when a wrong type is provided.
  E.g of a _type_ definition: _the attribute `telephone` is of type `String`_

  - _Rule_ validation - Based on a provided rule, it will validate if the content of the property/attribute is correct/valid. This implies the _type_ is already asserted/verified as valid.
  E.g. of a set of _rules_ would be _the attribute `telephone` is `required` and `numeric`_ (not the most proper rule, but you get the point 😉 ) 

So I see the first type of validation to be Model based, and a second one might be delegated to a method present at the business logic's level/layer.

Is that what we're saying?

**Comment by fahad19** [comment]
@mAiNiNfEcTiOn: that's exactly how we are seeing it too. thanks for putting it in better words.

**Comment by viacheslaff** [comment]
> I share similar views too. Validation can be separate from Models/Collections. Then the question comes, where does it go then?
> When defining Schema for a Model, you are already setting 'types' info for the fields. So putting validation rules there means the developer has to maintain things per 'field' only in one place.
> I liked seeing how Ecto (Elixir) did it with Changesets concept. It would be worth checking how they do it, and see if we can translate it into a meaningful API in this spec: https://hexdocs.pm/ecto/Ecto.Changeset.html

Types are a bit different from validation rules. Field cannot have value of invalid type, but field can contain invalid value (on frontend, at least, for intermediate user input). So maybe we can separate them. On the other hand, it's nice to keep them together, for readability, code reuse and ease of overview. For that, we can use either static field or named exports from modules.

```js
const PostSchema = createSchema({
  title: Types.string
});

const Post = createModel({
  schema: PostSchema
});

// option 1: static method (not sure if it should be part of schema or model)
Post.validationRules = { ... };

// option 2: named export
export default Post;
export PostValidationRules;
```

>> I'm a bit worried, that with current proposal model can contain invalid data although it has validation rules embedded. Maybe we can only restrict types in the model, but values can be arbitrary (i.e. for storing temporary values while user fills in a form), and then apply validation rules whenever necessary.
> This is something that came up before too. Unlike ORMs in backend, Models in the browser do need to contain user input as they happen. Think of a Post model being used to render a form:

I agree that a model should be able to contain invalid data. Also, because sometimes you need to validate fields depending on each other, and for that they should be stored somewhere.

Maybe we can restrict it only to writeable fields. Because invalid read-only fields don't make sense to me.

Regarding the example that you provided, I'd like to use it to show how we can extract validation from data structure:

```js
import { validateModel$ } from `frint-data-validation`; // for example 

export default observe(function (app) {
  const post = new Post({
    title: 'Hello World',
  });

  return streamProps()
    .set(
      post.get$(),
      postAttrs => ({ titleValue: postAttrs.title })
    )
    .set('handleTItleChange', post.setTitle)
    .set(
      validateModel$(post, Post.validationRules),
      errors => ({ validationErrors: errors })
     )
    .get$();
})(PostForm);
```

It's a small change, but it decouples validation from model. It doesn't make sense have validation and model together because we allow model to be invalid.

I wonder where type errors would go, though.

Also, as I mentioned earlier, I think it's better to validate model, not changes, because there might be dependant fields.

**Comment by viacheslaff** [comment]
> Yes. Methods need to be allowed in Models, that will be defined when creating the Model class.
> And by default, only methods defined in the Model will be allowed to change the attributes (values) to avoid unwanted mutations.

I see. Do we expect methods to be for writing values only (setters), or we are also going to allow methods for computing derived data OOP style, like `circle.getArea()`?

>> How about considering using instance properties? (because it's shorter and can be easier analyzed by IDE):

> This is something that I did previously in Tydel: http://tydel.js.org/intro/quickstart.html
> The problem with that kind of approach is, soon you get confused which property is actually a value (attribute), and which one is a method.

I think if you name methods properly, the confusion can be minimal. And again, if we only allow getters/setters methods, making models data structures only without other methods, it might not be a problem.

> And also limits the developer from using an attribute AND a method of the same name.

I don't think it's a good practice, so I wouldn't worry about it.

**Comment by reaktivo** [comment]
I would like to suggest going for a more functional approach, treating models as pure data (simple objects), this way there's no ambiguity in how they are represented when they are serialised or unserialised (when doing a network request, stored in local storage, or messaged thru web workers). Computed properties can be calculated at the moment the one's they depend on are defined.

Although I don't mind having the schema shape and rule definition in the same place, I do strongly feel we should separate between rule "engines" and schema + rule definitions. We should be able to share this definition across languages and have different implementations that work the same way, we can do this by limiting ourselves to JSON types, having for example.

```json
// User.json
{
  "user": {
    "name": {
      "string": true,
      "required": true,
      "in-range: [1, 128]
    },
    "age": {
      "min": [18]
    }
  }
}

// Post.json
{
  "title": "string",
  "body": "html",
  "author": "user"
}
```

Then having language specific implementations:

```js
// Types.js
export default {
  "string": function(value /*, key, model, [min, max]*/) {
    return typeof value === 'string';
  },
  "in-range": function(value, key, model, [min, max]) {
    const value = model[key];
    return value && value > min && value < max;
  },
  // etc
}
```

Another in Go Lang, etc.

**Comment by fahad19** [comment]
@viacheslaff: based on your inputs, here's the updated API that I can think of this.

From library's point of view:

```js
// library
const Types = {
  string: function (value) {
    if (typeof value !== 'string') {
      throw new Error('Invalid string!');
    }
  }
};

function createModel(options= {}) {
  class Model {
    constructor(attributes = {}) {
      this.attributes = attributes;
    }
    
    get(field) {
      this.attributes[field];
    }
    
    get$(field) {
      return Observable;
    }
    
    set(field, value) { // private method, not exposed to public
      
    }
  }
  
  return Model;
}

function validate$(model, rules = null) {
  if (!rules) {
    // default to statically defined validation rules
    rules = model.__proto__.constructor.validationRules;
  }
  
  return Observable.of([]); // errors
}
```

As a consumer:

```js
const Post = createModel({
  schema: {
    title: Types.string,
  },
  
  getTitle() {
    return this.get('title');
  },
  
  setTitle(newTitle) {
    this.set('title', newTitle); // set() is only accessible inside methods privately
  }
});

Post.validationRules = [ ];

const post = new Post({ title: 'Hello World' });
post.setTitle('Hello Universe'); // works
post.setTitle(123); // throws Error
post.get('title') === 'Hello Universe';
post.toJS(); // plain JS object of post.attributes
post.get$(); // Observable emitting post.attributes on changes

// validation


validate$(post).subscribe(errors => console.log(errors));
```

**Comment by fahad19** [comment]
@reaktivo: Models and Collection instances are expected to have a `.toJS()` method, that converts them to plain Object/Arrays.

**Comment by fahad19** [comment]
We will split the work into two separate packages:

* `frint-data`
* `frint-data-validation`

Work for `frint-data` has started in the branch of same name, and will land sometime soon.

After that we will work on `frint-data-validation`, which will work closely with the API of `frint-data`, but without having any strict ties to it.
