### ISSUE TITLE
Import modules individually from RxJS

### ISSUE THREAD

**Issue by fahad19** [Travix-International/frint#260]
This is something that @jvantillo mentioned few months ago. I will put them with enough explanation below for further discussions.

## Current situation

Currently, we import and use Observables like this:

```js
import { Observable } from 'rxjs';

function doSomething$() {
  return Observable.of(1, 2, 3)
    .filter(x => x % 2 === 1)
    .map(x => x * 2);
}
```

This means the whole RxJS library is always expected to be loaded, adding to our bundle size.

## Recommended approach

```js
import { Observable } from 'rxjs/Observable';
import { of } from 'rxjs/observable/of';
import { map } from 'rxjs/operator/map';
import { filter } from 'rxjs/operator/filter';

function doSomething$() {
  return Observable
    ::of(1, 2, 3)
    ::filter(x => x % 2 === 1)
    ::map(x => x * 2)
}
```

The snippet above makes use of the bind operator though, which is still in `stage-0`: https://github.com/tc39/proposal-bind-operator

---

Below, the discussion is from the side of Travix:

## Problem from our side

While the recommended approach works great for single bundles, our case is a bit different. We have multiple bundles for Apps, and a separate single `vendors.js` bundle that brings in all other third-party libraries (like RxJS), and used as Webpack's `externals`.

This allows all App developers to be able to use all the features of RxJS, without having to put any RxJS modules in their own bundles.

## Possible solution to the problem

To go for a smooth migration, we can keep a list of all possible RxJS import paths, and put them as `externals` in our Webpack configuration of the bundler. And until everything is imported the recommended way, we can keep loading the full RxJS library via `vendors.js`.

Once everyone has migrated, we can go further and track the usage of those imports, and reduce the `vendors.js` size significantly.

**Comment by fahad19** [comment]
## Two things to achieve:

* Make sure the migration goes smooth
* Don't break the existing docs showing how RxJS (and other libs) are loaded from CDN
* Don't break the examples

## To do that, we need to be able to:

* Have a shareable key/value pairs list that can be used by Webpack.

## How the list may look like:

Webpack's [`externals`](https://webpack.js.org/configuration/externals/) equivalent object:

```js
{
  // RxJS
  'rxjs/Observable': ['Rx', 'Observable'], // window.Rx.Observable
  'rxjs/operator/map': ['Rx', 'Observable', 'prototype', 'map'],
  
  // lodash
  'lodash/debounce': ['_', 'debounce'], // window._.debounce
}
```

## Question

How can we make this list shareable? All examples, and all our applications need them.

Shall we create a package called `frint-webpack-stuff` or something? If so, what should be the package's name?

**Comment by viacheslaff** [comment]
Good idea. But since we shrink the functionality RxJS provides by not bundling it, how do we define the functionality that we need to support (and consequently the one that we don't need to)?

**Comment by fahad19** [comment]
@viacheslaff: there are two ways to look at it.

## From the perspective of Frint

We don't. Any time we import some RxJS module in any `frint-*` package, we make sure that it is listed in the `frint-webpack-stuff/externals` module, so that the package's own `webpack.config.js` can access it when producing the dist file (like `frint-store.min.js`).

When producing dists, it should expect the full RxJS lib as available as `window.Rx`.

That's where the responsibility ends.

We are supporting both:

* CDN users who load `rx.min.js` and `frint-store.min.js` separately as script tags, and
* Users who bundle both RxJS and `frint-store` in a single `bundle.js`

## From the perspective of Travix

We have our own bundler. And we load our external libraries in `vendors.js` file.

When Apps are bundled, we will be feeding the `frint-webpack-stuff/externals` config to Webpack, and make sure individual imports are not duplicated in the bundles (for modules that are already available in `vendors.js` file).

If the App developer is using any module that we do not support, it will increase the bundle size (for Apps), and we would notice.

After one quarter of migration, we can figure out what are the most common imports, and only keep them in our vendors. Until then, we provide a graceful migration path to everyone.

RxJS will still be made available fully until the individual import migration is done.
