### ISSUE TITLE
Proposal: frint-react-native

### ISSUE THREAD

**Issue by fahad19** [Travix-International/frint#333]
**TL;DR**: Build mobile applications targeting iOS/Android with React Native, utilizing the same API from all FrintJS packages.

## Plain `react-native` example

```js
// index.js
import { AppRegistry } from 'react-native';

import Root from './components/Root';

AppRegistry.registerComponent('Foo', () => Root);
```

## Possible API with proposed `frint-react-native`

```js
// index.js
import App from './app'; // Frint App
import { register } from 'frint-react-native';

const app = new App();

register(app);
```

## Implementation

The `register` function would do something similar to what `render` does from existing `frint-react`.

It would get the `app` instance and set it in the root component's context, so that `observe` and other goodies from the FrintJS monorepo can be utilized seamlessly in the mobile application too.

**Comment by mAiNiNfEcTiOn** [comment]
😆
