### ISSUE TITLE
frint-react: Support `className` prop in Region component

### ISSUE THREAD

**Issue by fahad19** [Travix-International/frint#337]
## Currently

Regions are embedded in Components like this:

```js
<Region name="sidebar" />
```

## Proposed feature

Allow `className` to be passed too like a regular React component:

```js
<Region
  name="sidebar"
  className="region-sidebar"
/>
```

This would allow CSS to target those elements, which may come from external source (outside of the primary application):

```css
.region-sidebar {
  display: none;
}
```

**Comment by jvantillo** [comment]
+1 yes this would make it possible to target the region as a whole much more easily.
