### ISSUE TITLE
add `onLoad` event for app

### ISSUE THREAD

**Issue by vasilibrutsky** [Travix-International/frint#83]
It would be nice to add smth like `onLoad` event for app when it's just being loaded to page (when __FRINT_INIT__ action is dispatched, not when beforeMount is called)

we have now a problem with subscribing for message broker.

**Comment by fahad19** [comment]
if we do happen to add a lifecycle method like that, I think `initialize` would be a good one. we have that in Service, Factory and Model too.

**Comment by fahad19** [comment]
`initialize` method supported in App classes. Can be seen in `next` branch docs, which will land in v1.0: https://github.com/Travix-International/frint/tree/afa394b64a7b94a20ff692beb431c455d85e711d/src/core#arguments
